version: "3.1"

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: videomanager
      MYSQL_USER: videomanager
      MYSQL_PASSWORD: videomanager
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    ports:
      - 8080:8080